# Form implementation generated from reading ui file 'mainsklad.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from connector import c
import tovarcreation  # Импортируем файл tovars.py

class Ui_mainsklad(object):
    # НАСТРОЙКИ БАЗЫ ДАННЫХ - МЕНЯЙТЕ ЗДЕСЬ
    DB_CONFIG = {
        # Таблицы
        'table_tovar': 'tovar',
        'table_typetovar': 'typetovar',
        'table_manufacturer': 'manufacturer',
        'table_garantytype': 'garantytype',
        'table_charvalues': 'charvalues',
        'table_characters': 'characters',
        'table_typecharlist': 'typecharlist',
        'table_users': 'users',
        'table_roles': 'roles',

        # Столбцы таблицы tovar
        'col_tovar_id': 'ID',
        'col_tovar_name': 'Name',
        'col_tovar_manufacturer_id': 'ManufacturerID',
        'col_tovar_type_id': 'TypeID',
        'col_tovar_price': 'Price',
        'col_tovar_garanty_period': 'GarantyPeriod',
        'col_tovar_garanty_type_id': 'GarantyTypeID',
        'col_tovar_quantity': 'Quantity',

        # Столбцы таблиц справочников
        'col_reference_id': 'ID',
        'col_reference_value': 'Value',

        # Столбцы таблицы typecharlist
        'col_typecharlist_type_id': 'TypeID',
        'col_typecharlist_char_id': 'CharID',

        # Столбцы таблицы characters
        'col_characters_id': 'ID',
        'col_characters_value': 'Value',

        # Столбцы таблицы charvalues
        'col_charvalues_tovar_id': 'TovarID',
        'col_charvalues_char_id': 'CharID',
        'col_charvalues_value': 'Value',

        # Столбцы таблицы users
        'col_users_surname': 'Surname',
        'col_users_name': 'Name',
        'col_users_patronymic': 'Patronymic',
        'col_users_role': 'RoleID',

        # Столбцы таблицы roles
        'col_roles_id': 'ID',
        'col_roles_value': 'Value'
    }

    def setupUi(self, mainsklad):
        mainsklad.setObjectName("mainsklad")
        mainsklad.resize(866, 644)
        self.centralwidget = QtWidgets.QWidget(parent=mainsklad)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 60, 121, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 60, 301, 24))
        self.lineEdit.setObjectName("lineEdit")

        # Подключаем поиск при изменении текста
        self.lineEdit.textChanged.connect(self.search_tovar)

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 40, 151, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(520, 60, 301, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)

        # Настраиваем режимы изменения размера для tableWidget
        self.tableWidget.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidget.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Fixed)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 90, 491, 441))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtWidgets.QTableWidget.SelectionMode.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QTableWidget.SelectionBehavior.SelectRows)

        # Подключаем сигнал выбора строки
        self.tableWidget_2.itemSelectionChanged.connect(self.on_tovar_selected)

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 580, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 580, 200, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 580, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(760, 580, 100, 16))
        self.label_6.setObjectName("label_6")
        mainsklad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainsklad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")

        # Создаем действие для меню
        self.action_add_tovar = QtGui.QAction(parent=mainsklad)
        self.action_add_tovar.setObjectName("action_add_tovar")
        self.menu.addAction(self.action_add_tovar)

        mainsklad.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainsklad)
        self.statusbar.setObjectName("statusbar")
        mainsklad.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)

        # Устанавливаем заголовки для tableWidget
        self.tableWidget.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem("Характеристика"))
        self.tableWidget.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem("Значение"))

        # Устанавливаем фиксированную высоту строк для tableWidget
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)

        self.retranslateUi(mainsklad)
        QtCore.QMetaObject.connectSlotsByName(mainsklad)

        # Подключаем обработчик клика на меню
        self.action_add_tovar.triggered.connect(self.open_tovars_window)

        # Загружаем данные пользователя после setupUi
        self.load_user_data()

    def open_tovars_window(self):
        """Открывает окно добавления товара"""
        try:
            # Создаем новое окно
            self.tovars_window = QtWidgets.QMainWindow()
            # Используем класс Ui_AddTovar из tovarcreation.py
            self.tovars_ui = tovarcreation.Ui_AddTovar()
            self.tovars_ui.setupUi(self.tovars_window)
            self.tovars_window.show()

            print("Окно добавления товара открыто")
        except Exception as e:
            print(f"Ошибка при открытии окна добавления товара: {e}")
            # Если возникла ошибка, показываем сообщение
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setText("Не удалось открыть окно добавления товара")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_user_data(self):
        try:
            from window_manager import WindowManager

            window_manager = WindowManager()
            current_user_id = window_manager.get_current_userID()

            if current_user_id is None:
                self.label_4.setText("Не авторизован")
                self.label_6.setText("Гость")
                return

            config = self.DB_CONFIG

            query = f"""
            SELECT u.{config['col_users_surname']},
                u.{config['col_users_name']},
                u.{config['col_users_patronymic']},
                r.{config['col_roles_value']}
            FROM {config['table_users']} u
            JOIN {config['table_roles']} r ON u.{config['col_users_role']} = r.{config['col_roles_id']}
            WHERE u.{config['col_reference_id']} = %s
            """

            c.execute(query, (current_user_id,))
            user_data = c.fetchone()

            if user_data:
                surname, name, patronymic, role_name = user_data

                # Формируем ФИО
                fio = f"{surname} {name} {patronymic}"
                self.label_4.setText(fio)
                self.label_6.setText(role_name)

                print(f"Загружен пользователь: {fio}, роль: {role_name}")
            else:
                self.label_4.setText("Пользователь не найден")
                self.label_6.setText("Не определена")

        except Exception as e:
            print(f"Ошибка при загрузке данных пользователя: {e}")
            self.label_4.setText("Ошибка загрузки")
            self.label_6.setText("Ошибка")

    def retranslateUi(self, mainsklad):
        _translate = QtCore.QCoreApplication.translate
        mainsklad.setWindowTitle(_translate("mainsklad", "mainsklad"))
        self.label.setText(_translate("mainsklad", "Поиск по:"))
        self.comboBox.setItemText(0, _translate("mainsklad", "Артиклу"))
        self.comboBox.setItemText(1, _translate("mainsklad", "Имени"))
        self.label_2.setText(_translate("mainsklad", "Характеристики товара:"))
        self.label_3.setText(_translate("mainsklad", "Пользователь:"))
        self.label_4.setText(_translate("mainsklad", "Загрузка..."))
        self.label_5.setText(_translate("mainsklad", "Текущая роль:"))
        self.label_6.setText(_translate("mainsklad", "Загрузка..."))
        self.menu.setTitle(_translate("mainsklad", "Добавить товар в систему"))
        self.action_add_tovar.setText(_translate("mainsklad", "Добавить товар"))

        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("mainsklad", "Артикул"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("mainsklad", "Наименование"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("mainsklad", "Цена"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("mainsklad", "Кол-во на складе"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("mainsklad", "Гарантия"))

        self.tovar_stable()

    # Остальные методы остаются без изменений
    def search_tovar(self):
        """Поиск товаров по артикулу или имени"""
        try:
            search_text = self.lineEdit.text().strip()
            search_type = self.comboBox.currentText()

            config = self.DB_CONFIG

            if search_text == "":
                self.tovar_stable()
                return

            if search_type == "Артиклу":
                query = f"""
                SELECT t.*, ty.Value as TypeName, m.Value as ManufName, g.Value as GarantName
                FROM {config['table_tovar']} t
                LEFT JOIN {config['table_typetovar']} ty ON t.{config['col_tovar_type_id']} = ty.{config['col_reference_id']}
                LEFT JOIN {config['table_manufacturer']} m ON t.{config['col_tovar_manufacturer_id']} = m.{config['col_reference_id']}
                LEFT JOIN {config['table_garantytype']} g ON t.{config['col_tovar_garanty_type_id']} = g.{config['col_reference_id']}
                WHERE t.{config['col_tovar_id']} LIKE %s
                """
                params = (f"%{search_text}%",)
            else:
                query = f"""
                SELECT t.*, ty.Value as TypeName, m.Value as ManufName, g.Value as GarantName
                FROM {config['table_tovar']} t
                LEFT JOIN {config['table_typetovar']} ty ON t.{config['col_tovar_type_id']} = ty.{config['col_reference_id']}
                LEFT JOIN {config['table_manufacturer']} m ON t.{config['col_tovar_manufacturer_id']} = m.{config['col_reference_id']}
                LEFT JOIN {config['table_garantytype']} g ON t.{config['col_tovar_garanty_type_id']} = g.{config['col_reference_id']}
                WHERE t.{config['col_tovar_name']} LIKE %s
                   OR ty.Value LIKE %s
                   OR m.Value LIKE %s
                """
                params = (f"%{search_text}%", f"%{search_text}%", f"%{search_text}%")

            c.execute(query, params)
            result = c.fetchall()

            self.tableWidget_2.setRowCount(0)
            self.tableWidget_2.setRowCount(len(result))

            for i, row in enumerate(result):
                item = QtWidgets.QTableWidgetItem(str(row[0]))
                self.tableWidget_2.setItem(i, 0, item)

                type_name = row[8] if len(row) > 8 else ""
                manuf_name = row[9] if len(row) > 9 else ""
                item = QtWidgets.QTableWidgetItem(f"{type_name} {manuf_name} {row[1]}")
                self.tableWidget_2.setItem(i, 1, item)

                item = QtWidgets.QTableWidgetItem(str(row[4]))
                self.tableWidget_2.setItem(i, 2, item)

                item = QtWidgets.QTableWidgetItem(str(row[7]))
                self.tableWidget_2.setItem(i, 3, item)

                garant_name = row[10] if len(row) > 10 else ""
                item = QtWidgets.QTableWidgetItem(f"{row[5]} {garant_name}")
                self.tableWidget_2.setItem(i, 4, item)

        except Exception as e:
            print(f"Ошибка при поиске: {e}")

    def tovar_stable(self):
        """Заполнение таблицы товаров (все товары)"""
        try:
            config = self.DB_CONFIG

            query = f"""
            SELECT t.*, ty.Value as TypeName, m.Value as ManufName, g.Value as GarantName
            FROM {config['table_tovar']} t
            LEFT JOIN {config['table_typetovar']} ty ON t.{config['col_tovar_type_id']} = ty.{config['col_reference_id']}
            LEFT JOIN {config['table_manufacturer']} m ON t.{config['col_tovar_manufacturer_id']} = m.{config['col_reference_id']}
            LEFT JOIN {config['table_garantytype']} g ON t.{config['col_tovar_garanty_type_id']} = g.{config['col_reference_id']}
            """

            c.execute(query)
            result = c.fetchall()

            self.tableWidget_2.setRowCount(len(result))

            for i, row in enumerate(result):
                item = QtWidgets.QTableWidgetItem(str(row[0]))
                self.tableWidget_2.setItem(i, 0, item)

                type_name = row[8] if len(row) > 8 else ""
                manuf_name = row[9] if len(row) > 9 else ""
                item = QtWidgets.QTableWidgetItem(f"{type_name} {manuf_name} {row[1]}")
                self.tableWidget_2.setItem(i, 1, item)

                item = QtWidgets.QTableWidgetItem(str(row[4]))
                self.tableWidget_2.setItem(i, 2, item)

                item = QtWidgets.QTableWidgetItem(str(row[7]))
                self.tableWidget_2.setItem(i, 3, item)

                garant_name = row[10] if len(row) > 10 else ""
                item = QtWidgets.QTableWidgetItem(f"{row[5]} {garant_name}")
                self.tableWidget_2.setItem(i, 4, item)

        except Exception as e:
            print(f"Ошибка при загрузке товаров: {e}")

    def on_tovar_selected(self):
        """Обработчик выбора товара - загружает характеристики выбранного товара"""
        try:
            selected_items = self.tableWidget_2.selectedItems()
            if not selected_items:
                return

            tovar_id = int(selected_items[0].text())
            self.tableWidget.setRowCount(0)

            config = self.DB_CONFIG

            query = f"""
            SELECT ch.{config['col_characters_value']}, cv.{config['col_charvalues_value']}
            FROM {config['table_charvalues']} cv
            JOIN {config['table_characters']} ch ON cv.{config['col_charvalues_char_id']} = ch.{config['col_characters_id']}
            WHERE cv.{config['col_charvalues_tovar_id']} = %s
            """

            c.execute(query, (tovar_id,))
            characteristics = c.fetchall()

            self.tableWidget.setRowCount(len(characteristics))
            for i, (char_name, char_value) in enumerate(characteristics):
                item_name = QtWidgets.QTableWidgetItem(str(char_name))
                item_value = QtWidgets.QTableWidgetItem(str(char_value))

                self.tableWidget.setItem(i, 0, item_name)
                self.tableWidget.setItem(i, 1, item_value)

            print(f"Загружено {len(characteristics)} характеристик для товара ID: {tovar_id}")

        except Exception as e:
            print(f"Ошибка при загрузке характеристик: {e}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainsklad = QtWidgets.QMainWindow()
    ui = Ui_mainsklad()
    ui.setupUi(mainsklad)
    mainsklad.show()
    sys.exit(app.exec())
