# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from connector import c
from PyQt6.QtWidgets import QMessageBox

class Ui_regui(object):
    def setupUi(self, regui):
        regui.setObjectName("regui")
        regui.resize(603, 334)
        self.centralwidget = QtWidgets.QWidget(parent=regui)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 90, 181, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 130, 181, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 160, 121, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.toggled.connect(self.showPassword)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 200, 171, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.auth)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 90, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 130, 49, 16))
        self.label_2.setObjectName("label_2")
        regui.setCentralWidget(self.centralwidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.menubar = QtWidgets.QMenuBar(parent=regui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menubar.setObjectName("menubar")
        regui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=regui)
        self.statusbar.setObjectName("statusbar")
        regui.setStatusBar(self.statusbar)

        self.retranslateUi(regui)
        QtCore.QMetaObject.connectSlotsByName(regui)

    def retranslateUi(self, regui):
        _translate = QtCore.QCoreApplication.translate
        regui.setWindowTitle(_translate("regui", "Авторизация"))
        self.checkBox.setText(_translate("regui", "Показать пароль"))
        self.pushButton.setText(_translate("regui", "Авторизоваться"))
        self.label.setText(_translate("regui", "Логин"))
        self.label_2.setText(_translate("regui", "Пароль"))

    def showPassword(self, checked):
        if checked:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        else:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

    def auth(self):
        login = self.lineEdit.text().strip()
        password = self.lineEdit_2.text().strip()

        print(f"Попытка авторизации: логин='{login}', пароль='{password}'")

        # Проверяем существование пользователя
        c.execute("SELECT Login, Password, UserID FROM autorization WHERE Login = %s", (login,))
        result = c.fetchone()

        print(f"Результат из БД: {result}")

        if result is None:
            print("Пользователь не найден")
            QMessageBox.critical(None, "Ошибка", "Такого пользователя не существует", QMessageBox.StandardButton.Ok)
            return

        db_login, db_password, user_id = result

        if db_password != password:
            print(f"Неверный пароль. Ожидалось: '{db_password}', введено: '{password}'")
            QMessageBox.critical(None, "Ошибка", "Неверный пароль", QMessageBox.StandardButton.Ok)
            return

        # Разрешаем доступ только для пользователя root
        if login.lower() != "root":
            QMessageBox.critical(None, "Ошибка",
                               "Пользователь не найден",
                               QMessageBox.StandardButton.Ok)
            return

        try:
            # Получаем экземпляр WindowManager
            from window_manager import WindowManager
            window_manager = WindowManager()
            window_manager.set_current_userID(user_id)

            # Закрываем текущее окно
            main_window = self.centralwidget.window()
            main_window.close()

            # Открываем главное окно
            window_manager.show_mainsklad()

        except Exception as e:
            print(f"Ошибка при открытии главного окна: {e}")
            QMessageBox.critical(None, "Ошибка", f"Не удалось открыть главное окно: {str(e)}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    regui = QtWidgets.QMainWindow()
    ui = Ui_regui()
    ui.setupUi(regui)
    regui.show()
    sys.exit(app.exec())
