# Form implementation generated from reading ui file 'tovarcreation.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from connector import c, db


class Ui_AddTovar(object):
    def setupUi(self, AddTovar):
        AddTovar.setObjectName("AddTovar")
        AddTovar.resize(872, 777)
        self.centralwidget = QtWidgets.QWidget(parent=AddTovar)
        self.centralwidget.setObjectName("centralwidget")
        self.addTovarBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addTovarBtn.setGeometry(QtCore.QRect(10, 10, 211, 29))
        self.addTovarBtn.setObjectName("addTovarBtn")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 841, 701))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.manufacturerCombobox = QtWidgets.QComboBox(parent=self.groupBox)
        self.manufacturerCombobox.setGeometry(QtCore.QRect(110, 30, 491, 28))
        self.manufacturerCombobox.setObjectName("manufacturerCombobox")
        self.priceSpin = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.priceSpin.setGeometry(QtCore.QRect(660, 30, 111, 29))
        self.priceSpin.setMaximum(999999.0)
        self.priceSpin.setObjectName("priceSpin")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(610, 30, 41, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nameEdit.setGeometry(QtCore.QRect(110, 70, 701, 28))
        self.nameEdit.setObjectName("nameEdit")
        self.garantyCheckbox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.garantyCheckbox.setGeometry(QtCore.QRect(10, 110, 131, 31))
        self.garantyCheckbox.setObjectName("garantyCheckbox")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 110, 71, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.garantySpin = QtWidgets.QSpinBox(parent=self.groupBox)
        self.garantySpin.setGeometry(QtCore.QRect(220, 110, 51, 31))
        self.garantySpin.setMaximum(999999)
        self.garantySpin.setObjectName("garantySpin")
        self.garantyType = QtWidgets.QComboBox(parent=self.groupBox)
        self.garantyType.setGeometry(QtCore.QRect(290, 110, 311, 28))
        self.garantyType.setObjectName("garantyType")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(610, 110, 81, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.countSpin = QtWidgets.QSpinBox(parent=self.groupBox)
        self.countSpin.setGeometry(QtCore.QRect(700, 110, 111, 29))
        self.countSpin.setMaximum(999999)
        self.countSpin.setObjectName("countSpin")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 91, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.tovarTypeBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.tovarTypeBox.setGeometry(QtCore.QRect(120, 150, 481, 28))
        self.tovarTypeBox.setObjectName("tovarTypeBox")
        self.addNewType = QtWidgets.QPushButton(parent=self.groupBox)
        self.addNewType.setGeometry(QtCore.QRect(620, 150, 191, 29))
        self.addNewType.setObjectName("addNewType")
        self.newTypeGroup = QtWidgets.QTabWidget(parent=self.groupBox)
        self.newTypeGroup.setGeometry(QtCore.QRect(10, 180, 801, 481))
        self.newTypeGroup.setObjectName("newTypeGroup")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tovar_characters = QtWidgets.QTableWidget(parent=self.tab)
        self.tovar_characters.setGeometry(QtCore.QRect(20, 20, 751, 401))
        self.tovar_characters.setObjectName("tovar_characters")
        self.tovar_characters.setColumnCount(2)
        self.tovar_characters.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tovar_characters.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tovar_characters.setHorizontalHeaderItem(1, item)
        self.newTypeGroup.addTab(self.tab, "")
        self.newTypeGroupPage1 = QtWidgets.QWidget()
        self.newTypeGroupPage1.setObjectName("newTypeGroupPage1")
        self.label_7 = QtWidgets.QLabel(parent=self.newTypeGroupPage1)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 121, 31))
        self.label_7.setObjectName("label_7")
        self.newTypeName = QtWidgets.QLineEdit(parent=self.newTypeGroupPage1)
        self.newTypeName.setGeometry(QtCore.QRect(270, 10, 501, 28))
        self.newTypeName.setObjectName("newTypeName")
        self.charactersTable = QtWidgets.QTableWidget(parent=self.newTypeGroupPage1)
        self.charactersTable.setGeometry(QtCore.QRect(10, 50, 501, 391))
        self.charactersTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.charactersTable.setObjectName("charactersTable")
        self.charactersTable.setColumnCount(2)
        self.charactersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.charactersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.charactersTable.setHorizontalHeaderItem(1, item)
        self.label_8 = QtWidgets.QLabel(parent=self.newTypeGroupPage1)
        self.label_8.setGeometry(QtCore.QRect(530, 50, 251, 20))
        self.label_8.setObjectName("label_8")
        self.newCharName = QtWidgets.QLineEdit(parent=self.newTypeGroupPage1)
        self.newCharName.setGeometry(QtCore.QRect(530, 80, 251, 21))
        self.newCharName.setObjectName("newCharName")
        self.addNewCharBtn = QtWidgets.QPushButton(parent=self.newTypeGroupPage1)
        self.addNewCharBtn.setGeometry(QtCore.QRect(530, 110, 251, 29))
        self.addNewCharBtn.setObjectName("addNewCharBtn")
        self.addTypeBtn = QtWidgets.QPushButton(parent=self.newTypeGroupPage1)
        self.addTypeBtn.setGeometry(QtCore.QRect(530, 410, 251, 29))
        self.addTypeBtn.setObjectName("addTypeBtn")
        self.cancelChar = QtWidgets.QPushButton(parent=self.newTypeGroupPage1)
        self.cancelChar.setGeometry(QtCore.QRect(530, 380, 251, 29))
        self.cancelChar.setObjectName("cancelChar")
        self.newTypeGroup.addTab(self.newTypeGroupPage1, "")
        AddTovar.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddTovar)
        self.newTypeGroup.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AddTovar)


        self.setup_connections()

    def setup_connections(self):


        self.newTypeGroup.setVisible(False)


        self.addNewType.clicked.connect(self.show_new_type_group)


        self.cancelChar.clicked.connect(self.remove_last_characteristic)


        self.addNewCharBtn.clicked.connect(self.add_new_characteristic)


        self.addTypeBtn.clicked.connect(self.add_new_tovar_type)

        self.addTovarBtn.clicked.connect(self.add_tovar_to_system)


        self.tovarTypeBox.currentTextChanged.connect(self.load_tovar_characteristics)


        self.load_manufacturers()
        self.load_tovar_types()
        self.load_garanty_types()

        self.added_characteristics_ids = []

    def show_new_type_group(self):

        self.newTypeGroup.setVisible(True)
        self.groupBox.resize(841, 701)
        self.added_characteristics_ids.clear()


        self.load_characteristics()

    def remove_last_characteristic(self):

        try:
            if not self.added_characteristics_ids:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Нет добавленных характеристик для удаления")
                msg.setWindowTitle("Информация")
                msg.exec()
                return


            last_char_id = self.added_characteristics_ids[-1]


            char_query = "SELECT Value FROM characters WHERE ID = %s"
            c.execute(char_query, (last_char_id,))
            char_name_result = c.fetchone()
            char_name = char_name_result[0] if char_name_result else "неизвестная характеристика"


            delete_query = "DELETE FROM characters WHERE ID = %s"
            c.execute(delete_query, (last_char_id,))
            db.commit()


            self.added_characteristics_ids.pop()


            self.load_characteristics()


            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setText(f"Характеристика '{char_name}' удалена")
            msg.setWindowTitle("Успех")
            msg.exec()

            print(f"Удалена характеристика: {char_name} (ID: {last_char_id})")

        except Exception as e:
            print(f"Ошибка при удалении характеристики: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Ошибка при удалении характеристики")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_manufacturers(self):

        try:

            self.manufacturerCombobox.clear()


            self.manufacturerCombobox.addItem("")


            query = "SELECT Value FROM manufacturer ORDER BY Value"
            c.execute(query)
            manufacturers = c.fetchall()


            for manufacturer in manufacturers:
                self.manufacturerCombobox.addItem(manufacturer[0])

            print(f"Загружено {len(manufacturers)} производителей")

        except Exception as e:
            print(f"Ошибка при загрузке производителей: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setText("Ошибка загрузки производителей")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_tovar_types(self):

        try:

            self.tovarTypeBox.clear()


            self.tovarTypeBox.addItem("")


            query = "SELECT Value FROM typetovar ORDER BY Value"
            c.execute(query)
            tovar_types = c.fetchall()

            for tovar_type in tovar_types:
                self.tovarTypeBox.addItem(tovar_type[0])

            print(f"Загружено {len(tovar_types)} типов товаров")

        except Exception as e:
            print(f"Ошибка при загрузке типов товаров: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setText("Ошибка загрузки типов товаров")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_garanty_types(self):

        try:

            self.garantyType.clear()


            self.garantyType.addItem("")

            query = "SELECT Value FROM garantytype ORDER BY Value"
            c.execute(query)
            garanty_types = c.fetchall()


            for garanty_type in garanty_types:
                self.garantyType.addItem(garanty_type[0])

            print(f"Загружено {len(garanty_types)} типов гарантий")

        except Exception as e:
            print(f"Ошибка при загрузке типов гарантий: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setText("Ошибка загрузки типов гарантий")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_characteristics(self):

        try:

            selected_characteristics = set()
            for row in range(self.charactersTable.rowCount()):
                checkbox_item = self.charactersTable.item(row, 0)
                characteristic_item = self.charactersTable.item(row, 1)
                if checkbox_item and characteristic_item:
                    if checkbox_item.checkState() == QtCore.Qt.CheckState.Checked:
                        selected_characteristics.add(characteristic_item.text())


            self.charactersTable.setRowCount(0)

            query = "SELECT ID, Value FROM characters ORDER BY Value"
            c.execute(query)
            characteristics = c.fetchall()


            self.charactersTable.setRowCount(len(characteristics))


            for i, (char_id, char_name) in enumerate(characteristics):

                checkbox_item = QtWidgets.QTableWidgetItem()
                checkbox_item.setFlags(QtCore.Qt.ItemFlag.ItemIsUserCheckable | QtCore.Qt.ItemFlag.ItemIsEnabled)
                if char_name in selected_characteristics:
                    checkbox_item.setCheckState(QtCore.Qt.CheckState.Checked)
                else:
                    checkbox_item.setCheckState(QtCore.Qt.CheckState.Unchecked)

                self.charactersTable.setItem(i, 0, checkbox_item)


                name_item = QtWidgets.QTableWidgetItem(str(char_name))
                name_item.setFlags(QtCore.Qt.ItemFlag.ItemIsEnabled)
                self.charactersTable.setItem(i, 1, name_item)

            print(f"Загружено {len(characteristics)} характеристик из БД")

        except Exception as e:
            print(f"Ошибка при загрузке характеристик: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            msg.setText("Ошибка загрузки характеристик")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def load_tovar_characteristics(self):

        try:

            self.tovar_characters.setRowCount(0)

            selected_type = self.tovarTypeBox.currentText()
            if not selected_type:
                return


            type_query = "SELECT ID FROM typetovar WHERE Value = %s"
            c.execute(type_query, (selected_type,))
            type_result = c.fetchone()

            if not type_result:
                return

            type_id = type_result[0]


            query = """
            SELECT c.ID, c.Value
            FROM characters c
            JOIN typecharlist tcl ON c.ID = tcl.CharID
            WHERE tcl.TypeID = %s
            ORDER BY c.Value
            """
            c.execute(query, (type_id,))
            characteristics = c.fetchall()


            self.tovar_characters.setRowCount(len(characteristics))


            for i, (char_id, char_name) in enumerate(characteristics):

                name_item = QtWidgets.QTableWidgetItem(str(char_name))
                name_item.setFlags(QtCore.Qt.ItemFlag.ItemIsEnabled)
                self.tovar_characters.setItem(i, 0, name_item)


                value_item = QtWidgets.QTableWidgetItem("")
                value_item.setFlags(QtCore.Qt.ItemFlag.ItemIsEnabled | QtCore.Qt.ItemFlag.ItemIsEditable)
                self.tovar_characters.setItem(i, 1, value_item)

            print(f"Загружено {len(characteristics)} характеристик для типа '{selected_type}'")

        except Exception as e:
            print(f"Ошибка при загрузке характеристик товара: {e}")

    def add_new_characteristic(self):

        try:

            characteristic_name = self.newCharName.text().strip()


            if not characteristic_name:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Введите название характеристики")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return

            check_query = "SELECT ID FROM characters WHERE Value = %s"
            c.execute(check_query, (characteristic_name,))
            existing_char = c.fetchone()

            if existing_char:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Такая характеристика уже существует")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return


            insert_query = "INSERT INTO characters (Value) VALUES (%s)"
            c.execute(insert_query, (characteristic_name,))
            db.commit()


            new_char_id = c.lastrowid
            self.added_characteristics_ids.append(new_char_id)


            self.newCharName.clear()


            self.load_characteristics()


            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setText("Характеристика успешно добавлена")
            msg.setWindowTitle("Успех")
            msg.exec()

            print(f"Добавлена характеристика: {characteristic_name} (ID: {new_char_id})")

        except Exception as e:
            print(f"Ошибка при добавлении характеристики: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Ошибка при добавлении характеристики")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def add_new_tovar_type(self):

        try:

            type_name = self.newTypeName.text().strip()


            if not type_name:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Введите название типа товара")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return


            check_query = "SELECT ID FROM typetovar WHERE Value = %s"
            c.execute(check_query, (type_name,))
            existing_type = c.fetchone()

            if existing_type:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Такой тип товара уже существует")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return


            insert_query = "INSERT INTO typetovar (Value) VALUES (%s)"
            c.execute(insert_query, (type_name,))


            new_type_id = c.lastrowid


            self.add_type_characteristics(new_type_id)

            db.commit()


            self.newTypeName.clear()


            self.load_tovar_types()


            self.reset_characteristics_selection()


            self.added_characteristics_ids.clear()


            self.hide_new_type_group()


            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setText("Тип товара успешно добавлен")
            msg.setWindowTitle("Успех")
            msg.exec()

            print(f"Добавлен тип товара: {type_name}")

        except Exception as e:
            print(f"Ошибка при добавлении типа товара: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Ошибка при добавлении типа товара")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def add_type_characteristics(self, type_id):
        """Добавляет связи между типом товара и выбранными характеристиками"""
        try:

            for row in range(self.charactersTable.rowCount()):
                checkbox_item = self.charactersTable.item(row, 0)
                characteristic_item = self.charactersTable.item(row, 1)


                if checkbox_item and checkbox_item.checkState() == QtCore.Qt.CheckState.Checked:
                    characteristic_name = characteristic_item.text()


                    char_query = "SELECT ID FROM characters WHERE Value = %s"
                    c.execute(char_query, (characteristic_name,))
                    char_result = c.fetchone()

                    if char_result:
                        char_id = char_result[0]


                        insert_query = "INSERT INTO typecharlist (TypeID, CharID) VALUES (%s, %s)"
                        c.execute(insert_query, (type_id, char_id))
                        print(f"Добавлена связь: TypeID={type_id}, CharID={char_id}")

        except Exception as e:
            print(f"Ошибка при добавлении связей характеристик: {e}")
            raise e

    def reset_characteristics_selection(self):

        for row in range(self.charactersTable.rowCount()):
            checkbox_item = self.charactersTable.item(row, 0)
            if checkbox_item:
                checkbox_item.setCheckState(QtCore.Qt.CheckState.Unchecked)

    def hide_new_type_group(self):

        self.newTypeGroup.setVisible(False)

        self.groupBox.resize(841, 200)

    def retranslateUi(self, AddTovar):
        _translate = QtCore.QCoreApplication.translate
        AddTovar.setWindowTitle(_translate("AddTovar", "Добавление товара"))
        self.addTovarBtn.setText(_translate("AddTovar", "Добавить товар в систему"))
        self.groupBox.setTitle(_translate("AddTovar", "Основные сведения"))
        self.label.setText(_translate("AddTovar", "Производитель:"))
        self.label_2.setText(_translate("AddTovar", "Цена:"))
        self.label_3.setText(_translate("AddTovar", "Наименование:"))
        self.garantyCheckbox.setText(_translate("AddTovar", "Гарантия на товар"))
        self.label_4.setText(_translate("AddTovar", "Гарантия:"))
        self.label_5.setText(_translate("AddTovar", "Количество:"))
        self.label_6.setText(_translate("AddTovar", "Тип товара:"))
        self.addNewType.setText(_translate("AddTovar", "Добавить новый тип"))
        item = self.tovar_characters.horizontalHeaderItem(0)
        item.setText(_translate("AddTovar", "Характеристика"))
        item = self.tovar_characters.horizontalHeaderItem(1)
        item.setText(_translate("AddTovar", "Значение"))
        self.newTypeGroup.setTabText(self.newTypeGroup.indexOf(self.tab), _translate("AddTovar", "Характеристики товара"))
        self.label_7.setText(_translate("AddTovar", "Наименование:"))
        item = self.charactersTable.horizontalHeaderItem(0)
        item.setText(_translate("AddTovar", "Выбор"))
        item = self.charactersTable.horizontalHeaderItem(1)
        item.setText(_translate("AddTovar", "Характеристика"))
        self.label_8.setText(_translate("AddTovar", "Новая характеристика:"))
        self.addNewCharBtn.setText(_translate("AddTovar", "Добавить"))
        self.addTypeBtn.setText(_translate("AddTovar", "Применить изменения"))
        self.cancelChar.setText(_translate("AddTovar", "Отменить действие"))

        self.newTypeGroup.setTabText(self.newTypeGroup.indexOf(self.newTypeGroupPage1), _translate("AddTovar", "Новый тип товара"))


    def add_tovar_to_system(self):
        try:

            if not self.nameEdit.text().strip():
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Введите данные товара")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return

            if not self.tovarTypeBox.currentText():
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Выберите тип товара")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return


            name = self.nameEdit.text().strip()
            manufacturer = self.manufacturerCombobox.currentText()
            price = self.priceSpin.value()
            tovar_type = self.tovarTypeBox.currentText()
            quantity = self.countSpin.value()


            has_garanty = self.garantyCheckbox.isChecked()
            garanty_period = self.garantySpin.value() if has_garanty else 0
            garanty_type = self.garantyType.currentText() if has_garanty else ""


            manufacturer_id = None
            if manufacturer:
                query = "SELECT ID FROM manufacturer WHERE Value = %s"
                c.execute(query, (manufacturer,))
                result = c.fetchone()
                if result:
                    manufacturer_id = result[0]


            type_query = "SELECT ID FROM typetovar WHERE Value = %s"
            c.execute(type_query, (tovar_type,))
            type_result = c.fetchone()
            if not type_result:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setText("Ошибка: тип товара не найден")
                msg.setWindowTitle("Ошибка")
                msg.exec()
                return
            type_id = type_result[0]


            garanty_type_id = None
            if garanty_type:
                query = "SELECT ID FROM garantytype WHERE Value = %s"
                c.execute(query, (garanty_type,))
                result = c.fetchone()
                if result:
                    garanty_type_id = result[0]


            insert_tovar_query = """
            INSERT INTO tovar (Name, ManufacturerID, TypeID, CostValue, GarantyValue, GarantyTypeID, Count)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """
            c.execute(insert_tovar_query, (name, manufacturer_id, type_id, price, garanty_period, garanty_type_id, quantity))
            tovar_id = c.lastrowid


            self.save_tovar_characteristics(tovar_id, type_id)

            db.commit()


            self.nameEdit.clear()
            self.manufacturerCombobox.setCurrentIndex(0)
            self.tovarTypeBox.setCurrentIndex(0)
            self.priceSpin.setValue(0)
            self.countSpin.setValue(0)
            self.garantyCheckbox.setChecked(False)
            self.garantySpin.setValue(0)
            self.garantyType.setCurrentIndex(0)


            self.tovar_characters.setRowCount(0)


            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setText("Товар успешно добавлен в систему")
            msg.setWindowTitle("Успех")
            msg.exec()

            print(f"Добавлен товар: {name} (ID: {tovar_id})")

        except Exception as e:
            print(f"Ошибка при добавлении товара: {e}")

            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Ошибка при добавлении товара")
            msg.setInformativeText(str(e))
            msg.setWindowTitle("Ошибка")
            msg.exec()

    def save_tovar_characteristics(self, tovar_id, type_id):

        try:

            query = """
            SELECT c.ID, c.Value
            FROM characters c
            JOIN typecharlist tcl ON c.ID = tcl.CharID
            WHERE tcl.TypeID = %s
            ORDER BY c.Value
            """
            c.execute(query, (type_id,))
            characteristics = c.fetchall()


            for row in range(self.tovar_characters.rowCount()):
                if row < len(characteristics):
                    char_id = characteristics[row][0]
                    value_item = self.tovar_characters.item(row, 1)

                    if value_item:
                        value = value_item.text().strip()


                        if value:
                            insert_query = "INSERT INTO charvalues (TovarID, CharID, Value) VALUES (%s, %s, %s)"
                            c.execute(insert_query, (tovar_id, char_id, value))
                            print(f"Сохранена характеристика: TovarID={tovar_id}, CharID={char_id}, Value={value}")

        except Exception as e:
            print(f"Ошибка при сохранении характеристик товара: {e}")
            raise e

    def save_tovar_characteristics(self, tovar_id, type_id):

        try:

            query = """
            SELECT c.ID, c.Value
            FROM characters c
            JOIN typecharlist tcl ON c.ID = tcl.CharID
            WHERE tcl.TypeID = %s
            """
            c.execute(query, (type_id,))
            characteristics = c.fetchall()


            for row in range(self.tovar_characters.rowCount()):
                if row < len(characteristics):
                    char_id = characteristics[row][0]
                    value_item = self.tovar_characters.item(row, 1)

                    if value_item and value_item.text().strip():
                        value = value_item.text().strip()


                        insert_query = "INSERT INTO charvalues (TovarID, CharID, Value) VALUES (%s, %s, %s)"
                        c.execute(insert_query, (tovar_id, char_id, value))
                        print(f"Сохранена характеристика: TovarID={tovar_id}, CharID={char_id}, Value={value}")

        except Exception as e:
            print(f"Ошибка при сохранении характеристик товара: {e}")
            raise e

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddTovar = QtWidgets.QMainWindow()
    ui = Ui_AddTovar()
    ui.setupUi(AddTovar)
    AddTovar.show()
    sys.exit(app.exec())
